apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy

spec:
  replicas: 1

  selector:
    matchLabels:
      service: reverse-proxy

  template:
    metadata:
      labels:
        service: reverse-proxy
    spec:
      containers:
        # containers to run in the Pods
        - name: reverse-proxy
          image: hungapp/reverse-proxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

      restartPolicy: Always
